### ISSUE TITLE
Clarify vim namespace in README code snippet

### ISSUE THREAD

**Issue by gbroques** [doums/lsp_spinner.nvim#6]
Hi, thanks for creating this project!

The code is relatively simple and seems to be just what I want — an LSP spinner.

One minor suggestion for improvement would be to clarify the [*Setup* code  snippet](https://github.com/doums/lsp_spinner.nvim/blob/main/README.md?plain=1#L41) in the README:

```lua
-- ...

-- This assumes "local lsp = vim.lsp" at the top of the script.
local capabilities = lsp.protocol.make_client_capabilities()

-- ...
```

It would be clearer for a beginner or novice to either:

1. include `local lsp = vim.lsp` at the top of the code snippet.
2. or use `vim.lsp.protocol` instead.

I'm happy to contribute a PR for this if desriable.

Thanks again! :)

**Comment by doums** [comment]
Hi, you're welcome → fixed by https://github.com/doums/lsp_spinner.nvim/commit/53c4a703e7f14dd4842a69b128195786367d1a29
