### ISSUE TITLE
Return single spinner if there's work in progress for any LSP client and omit LSP client names

### ISSUE THREAD

**Issue by gbroques** [doums/lsp_spinner.nvim#7]
Currently the `status` and `buf_status` functions exposed by this module return:

1. the LSP client name(s) (e.g. `lua_ls`)
2. followed by a spinner if there is work in progress for theclient.

I'm creating a minimal statusline where I don't want to display the LSP client name(s), and work in progress for each client.

I only want a single spinner if there's work in progress for *any* LSP client.

Do you think we could make this plugin more configurable to support this?

---

Other use-cases I had were:

1. Displaying some other text like "LSP" in-lieu of the LSP client name(s).
2. and making the spinner to the left of the text, instead of the right (e.g. "/ lua_ls").

However, allowing this plugin to return a single spinner if there's progress for *any* LSP client would address (1) and (2).

This plugin is simple enough where I could probably fork and modify it, but I wanted to get your thoughts on this.

**Comment by doums** [comment]
> Do you think we could make this plugin more configurable to support this?

Hi, I'm just about releasing a new plugin that does exactly that. Providing a simple spinner whenever there are some work in progress for any active LSP.

> Displaying some other text like "LSP" in-lieu of the LSP client name(s).
> and making the spinner to the left of the text, instead of the right (e.g. "/ lua_ls").

You should be able to customize that using your statusline's plugin API. It is out of the scope of the incoming plugin.

**Comment by gbroques** [comment]
> Hi, I'm just about releasing a new plugin that does exactly that. Providing a simple spinner whenever there are some work in progress for any active LSP.
> 
> >

@doums Great! I'll be on the lookout for that. :)

**Comment by doums** [comment]
@gbroques https://github.com/doums/lswip.nvim
